project:
  type: website
  output-dir: docs

website:
  title: "Dungeons & Dragons AI Assistant"
  description: "A web-based AI assistant for Dungeons & Dragons"
  navbar:
    left:
      - href: index.qmd
        text: '<i class="bi bi-house"></i> Home'
      - href: D&D Chat Bot.qmd
        text: '<i class="bi bi-robot"></i> D&D Chat Bot'
      - href: Midterm.qmd
        text: '<i class="bi bi-gear"></i> Midterm'
      - href: Final.qmd
        text: '<i class="bi bi-mortarboard-fill"></i> Final'
      - href: Roadmap.qmd
        text: '<i class="bi bi-map"></i> Roadmap'

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    includes:
      in-header: bootstrap-icons.html
    # code-overflow: wrap   # fuerza el ‹wrap› en TODO el HTML
    code-width: 80  # 80 caracteres antes de envolver

format-options:
  editor:
    format-on-save: false