---
title: "Midterm"
format: html
---

**A web-based AI assistant for Dungeons & Dragons**  
*Knowledge is Our Quest. Dungeons are Our Dataset.*

---

##  Problem Statement?

When playing D&D the worst part is when your immersion is broken because someone has a niche rules question and you need to open the 
book and find some obscure rules or interaction. 

---

##  What is D&D? 

Dungeons & Dragons (D&D) is a collaborative storytelling game where you and your friends pretend to be adventurers in a fantasy world, and then immediately get sidetracked trying to bribe a goblin with cheese or argue over whether a horse can climb stairs.

<iframe width="588" height="1074" src="https://www.youtube.com/embed/S-QldbzLSEc" title="Deb shows Jon D&amp;D in 1m #dnd  #dnd5e  #pathfinder  #ttrpg  #gaming  #jonbernthal  #deborahannwoll" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

---

## Project Goal

In 10 weeks create a light weight LLM chatbot that can be used to answer combat questions, spell descriptions and effects, NPC generation, character generation, and virtual dice rolling. 

[Return to the Home Page to view our grand vision](index.qmd)

---

## Project Outline

Using ChatGPT we broke down the project into biweekly goals that we could then subdivide among the team. 

1. Core Foundation - Setup project structure and gather required documents to supply to RAG model.
2. Game Modules - Divide the information into different files for testing and uploading (spells, character info, and combat).
3. Agent Memory & UI - Develop session memory so context is preserved for different sessions.
4. Stretch Goals - Initative/ combat turn tracker, map management, and VTT integration.  

---

## Core Foundation (Weeks 1-2)

1. Project Setup
2. Load D&D Data
3. Dice Roller Module
4. LLM Integration
5. Basic Prompt Template Design
6. Command Line Interface

---

## Game Modules (Weeks 3-4)

1. Spell Lookup System
2. Character Generator
3. NPC Generator
4. (Basic) Combat Helper
5. Connect to the LLM Agent
6. Test Scenarios/ Model Evaluation

---

## Agent Memory (Weeks 5-6)

1. Add Conversation Memory
2. Basic Web UI
3. Add Conversation Persistence (Save/ Load Data)
4. Session State Management
5. Seamless Command Handling Layer
6. Player Logging & History 

---

## Stretch Goals (Weeks 7+)

1. Initiative & Combat Turn Tracker
2. Map/ Token Management
3. VTT Integration
4. Multi-Entity Management
5. UI Dashboard (Combat View)
6. Game Session Export